django_sql_dashboards/urls.py
# -*- coding: UTF-8 -*-

from __future__ import absolute_import, division, print_function

from django.conf.urls import patterns, url
from django_sql_dashboards.settings import SQL_DASHBOARDS_MEDIA_ROOT


urlpatterns = patterns(
    '',
    url(r'^$', 'django_sql_dashboards.views.home', name='sql_dashboards_home'),
    url(r'^query/?$', 'django_sql_dashboards.views.query_view', name='query_all'),
    url(r'^query/add/?$', 'django_sql_dashboards.views.query_editor', name='query_editor'),
    url(r'^query/delete/(\d+)$', 'django_sql_dashboards.views.query_delete', name='query_delete'),
    url(r'^query/edit/(\d+)$', 'django_sql_dashboards.views.query_editor', name='query_editor'),
    url(r'^query/custom/(\d+)$', 'django_sql_dashboards.views.query_custom', name='query_custom'),
    url(r'^query/to_highcharts/(\d+)?$', 'django_sql_dashboards.views.to_highcharts', name='to_highcharts'),


    url(r'^dashboard/?$', 'django_sql_dashboards.views.dashboard_view', name='dashboard_all'),
    url(r'^dashboard/add/?$', 'django_sql_dashboards.views.dashboard_create', name='dashboard_editor'),
    url(r'^dashboard/delete/(\d+)$', 'django_sql_dashboards.views.dashboard_delete', name='dashboard_delete'),
    url(r'^dashboard/edit/(\d+)$', 'django_sql_dashboards.views.dashboard_editor', name='dashboard_editor'),
    url(r'^dashboard/(\d+)/delete_query/(\d+)$', 'django_sql_dashboards.views.dashboard_delete_query', name='dashboard_delete_query'),
    url(r'^dashboard/(\d+)/change_order$', 'django_sql_dashboards.views.dashboard_editor_change_order', name='dashboard_editor_change_order'),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': SQL_DASHBOARDS_MEDIA_ROOT
    }),

    url(r'^test_query$', 'django_sql_dashboards.views.test_query', name='test_query'),

    url(r'.*', 'django_sql_dashboards.views.default', name='default'),
)

django_sql_dashboards/models.py
# -*- coding: UTF-8 -*-

from __future__ import absolute_import, division, print_function

import pickle
import datetime
import logging
import decimal
import pandas

from django.db import models
from django.template import Context, loader
from django.contrib.auth.models import User
from picklefield.fields import PickledObjectField
from dateutil import tz

from .db import DB

logger = logging.getLogger("sql-dashboards")


class DbConfig(models.Model):
    name = models.CharField(max_length=255, primary_key=True)
    host = models.CharField(max_length=255)
    user = models.CharField(max_length=255)
    passwd = models.CharField(max_length=255)
    db = models.CharField(max_length=255)

    ts_create = models.DateTimeField(auto_now_add=True)
    ts_update = models.DateTimeField(auto_now_add=True, auto_now=True)

    class Meta:
        ordering = ["name"]

    def getDb(self):
        return DB(host=self.host, user=self.user, passwd=self.passwd, db=self.db)

    def __unicode__(self):
        return "%s (%s@%s:%s)" % (self.name, self.user, self.host, self.db)


class Query(models.Model):
    TYPE_CHOICES = (
        ('table', 'Table'),
        ('line', 'Line Chart'),
        ('area', 'Area Chart'),
        ('column', 'Column Chart'),
        ('bar', 'Bar Chart')
    )
    db = models.ForeignKey(DbConfig)
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255, blank=True)
    xlegend = models.CharField(max_length=255, blank=True)
    ylegend = models.CharField(max_length=255, blank=True)
    type = models.CharField(max_length=255, choices=TYPE_CHOICES)
    query = models.TextField(blank=True)
    creator = models.ForeignKey(User)

    ts_create = models.DateTimeField(auto_now_add=True)
    ts_update = models.DateTimeField(auto_now_add=True, auto_now=True)

    public = models.BooleanField(default=True)

    legend_align = models.CharField(max_length=64, default='right', choices=(('top', 'Top'), ('left', 'Left'), ('bottom', 'Bottom'), ('right', 'Right'), ))
    cache_ttl = models.IntegerField(default=0, choices=((0, "No cache"), (60, "1 minute"), (300, "5 minutes"), (3600, "1 hour"), (86400, "1 day"), (7 * 86400, "1 week")))

    custom = models.BooleanField(default=False)
    pivot = models.BooleanField(default=False)

    def __init__(self, *args, **kwargs):
        super(Query, self).__init__(*args, **kwargs)
        self.data, self.headers, self.obj = None, None, None

    def execute(self, custom_data=None, cached=True):
        if cached:
            history = QueryHistory.objects.filter(query=self).order_by("-ts_update")[:1]
            if len(history):
                if (datetime.datetime.now().replace(tzinfo=tz.tzlocal()) - history[0].ts_update).seconds <= self.cache_ttl:
                    return pickle.loads(history[0].data)

        if self.custom:
            data = self.db.getDb().hquery(self.query % custom_data)
        else:
            data = self.db.getDb().hquery(self.query)
            if self.pivot:
                if len(data[1]) != 3 and self.pivot:
                    raise Exception("A pivot query must have 3 columns, %s columns given" % len(data[1]))
                df = pandas.DataFrame(list(data[0]), columns=data[1])
                df = df.pivot(index=data[1][0], columns=data[1][1], values=data[1][2]).reset_index().fillna(0)
                data = df.as_matrix(), df.columns
        if data:
            if self.id:
                QueryHistory.objects.filter(query=self).delete()
                QueryHistory(query=self, data=pickle.dumps(data)).save()
        return data

    def getAll(self, custom_data=None):
        try:
            ret = self.execute(custom_data=custom_data)
        except Exception as e:
            ret = None
            self.error = e
            logger.error("Cannot execute %(self)s, %(e)s" % locals())

        if ret:
            self.data, self.headers = ret
            self.obj = {
                "title": self.title,
                "subtitle": self.subtitle,
                "xlegend": self.xlegend,
                "ylegend": self.ylegend,
                "type": self.type,
                "legend_align": self.legend_align
            }
            self.obj["categories"] = [i[0] for i in self.data]
            self.obj["series"] = [{"name": self.headers[i], "data": [row[i] for row in self.data]} for i in range(1, len(self.headers))]

    def __unicode__(self):
        return self.title

    def toHighcharts(self):
        id_div = "id_query_%s" % self.id
        try:
            data, headers, obj = self.data, self.headers, self.obj
            if self.type == "table":
                return loader.get_template('django_sql_dashboards/table.html').render(Context(locals()))
            for serie in obj["series"]:
                for x in serie["data"]:
                    if not isinstance(x, (int, long, decimal.Decimal, float)):
                        raise Exception("Not properly formatted. Maybe null fields ?")
            return loader.get_template('django_sql_dashboards/highcharts.html').render(Context(locals()))
        except Exception as e:
            logger.error(str(e))
            return loader.get_template('django_sql_dashboards/query_error.html').render(Context(locals()))

    def toD3(self):
        id_div = "id_query_%s" % self.id
        data, headers, obj = self.getAll()
        if self.type == "table":
            return loader.get_template('django_sql_dashboards/table.html').render(Context(locals()))
        return loader.get_template('django_sql_dashboards/d3.html').render(Context(locals()))


class Dashboard(models.Model):
    title = models.CharField(max_length=255, blank=True)
    column_nb = models.IntegerField(choices=((1, 1), (2, 2), (3, 3), (4, 4), (6, 6)))
    creator = models.ForeignKey(User)

    def __init__(self, *args, **kwargs):
        super(Dashboard, self).__init__(*args, **kwargs)
        self.queries = None

    def __unicode__(self):
        return self.title

    def getColumnSize(self):
        return 12 / self.column_nb

    def getQueries(self):
        self.queries = [i.query for i in self.dashboardquery_set.all().order_by("order_id")]


class DashboardQuery(models.Model):
    dashboard = models.ForeignKey(Dashboard)
    query = models.ForeignKey(Query)
    order_id = models.IntegerField()

    class Meta:
        unique_together = ["dashboard", "query"]


class QueryHistory(models.Model):
    query = models.ForeignKey(Query)
    data = PickledObjectField()
    ts_create = models.DateTimeField(auto_now_add=True)
    ts_update = models.DateTimeField(auto_now_add=True, auto_now=True)

django_sql_dashboards/forms.py
# -*- coding: UTF-8 -*-

from __future__ import absolute_import, division, print_function

from django import forms
from django.conf import settings
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, HTML
from crispy_forms.bootstrap import Accordion, AccordionGroup

from .models import Query, Dashboard


class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        widgets = {'query': forms.Textarea(attrs={'cols': 90, 'rows': 4})}
        exclude = ("creator",)

    def __init__(self, *args, **kwargs):
        super(QueryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            ButtonHolder(
                Submit('run', 'Run'),
                Submit('save', 'Save'),
                Submit('run_save', 'Run & Save'),
                HTML("""<a href="%s/query/add" class="btn btn-success">+ Add</a>""" % settings.SQL_DASHBOARDS_PREFIX),
            ),
            HTML("<br>"),
            Fieldset('', 'db', 'title', 'type', 'query', 'pivot'),
            Accordion(AccordionGroup('Other options', 'subtitle', 'xlegend', 'ylegend', 'public', 'legend_align', 'cache_ttl')),
            HTML("<br>"),
            ButtonHolder(
                Submit('run', 'Run'),
                Submit('save', 'Save'),
                Submit('run_save', 'Run & Save'),
                HTML("""<a href="%s/query/add" class="btn btn-success">+ Add</a>""" % settings.SQL_DASHBOARDS_PREFIX),
            ),
        )

    def save(self, user, *args, **kwargs):
        inst = super(QueryForm, self).save(commit=False)
        inst.creator = user
        if kwargs.get("commit", False):
            inst.save()
        return inst


class QueryAddForm(forms.Form):
    query = forms.ModelChoiceField(queryset=Query.objects.all())

    def __init__(self, *args, **kwargs):
        super(QueryAddForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('add', 'Add'))


class DashboardForm(forms.ModelForm):
    class Meta:
        model = Dashboard
        exclude = ["creator"]

    def __init__(self, *args, **kwargs):
        super(DashboardForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('add', 'Create Dashboard'))

    def save(self, user, *args, **kwargs):
        inst = super(DashboardForm, self).save(commit=False)
        inst.creator = user
        if kwargs.get("commit", False):
            inst.save()
        return inst


class CustomQueryForm(forms.Form):
    limit = forms.IntegerField(required=False, initial=10)

    def __init__(self, query, *args, **kwargs):
        super(CustomQueryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        field_set = Fieldset('')
        has_limit = "%(limit)s" in query.query
        if has_limit:
            field_set.fields.append('limit')
        self.helper.layout = Layout(
            field_set,
            ButtonHolder(Submit('run', 'Run')),
        )

django_sql_dashboards/templates/django_sql_dashboards/dashboard_all.html
<style>
.listing ul{
  list-style-type: circle;
  padding:0 0 0 10;
  font-size: 12px;
}
.listing .selected {
  font-weight: bold;
}
</style>
{% load pagination_tags %}

<h3><a href="{{SQL_DASHBOARDS_PREFIX}}/dashboard/">Dashboard</a> <a class="btn btn-success btn-sm" href="{{SQL_DASHBOARDS_PREFIX}}/dashboard/add"><span class="glyphicon glyphicon-plus"></span> Add</a></h3>
{% if dashboard_filter %}
{% autopaginate dashboard_filter.qs 10 as filter_list %}
<div class="col-lg-8 span8">
  <table class="table table-condensed">
    <tr><th>Title</th><th>Creator</th><th>Action</th></tr>
  {% for obj in filter_list %}
    <tr>
      <td><a href="{{SQL_DASHBOARDS_PREFIX}}/dashboard/edit/{{obj.id}}">{{obj.title}}</a></td>
      <td>{{obj.creator}}</td>
      <td><a class="btn btn-danger btn-xs" href="{{SQL_DASHBOARDS_PREFIX}}/dashboard/delete/{{obj.id}}" onclick="return confirm('Sure you want to delete {{obj.title|escapejs}}?')"><span class="glyphicon glyphicon-minus"></span> Delete</a></td>
    </tr>
  {% endfor %}
  </table>
  {% paginate %}
</div>
<div class="col-lg-2 span2 well listing">
  {{ dashboard_filter.form.as_p }}
</div>
{% endif %}

django_sql_dashboards/templates/django_sql_dashboards/dashboard_editor.html
{% extends "base.html" %}

{% block body %}
  
  <style>
    .highlight {
      padding: 3px;
      margin-bottom: 14px;
      background-color: #f7f7f9;
      border: 1px solid #e1e1e8;
      border-radius: 4px;
    }

    .highlight:hover {
      cursor:pointer;
    }
    #sortable { list-style-type: none; margin: 0; padding: 0; }
  </style>
  <script src="{{SQL_DASHBOARDS_PREFIX}}/static/jquery-ui.js"></script>
  <script>
  var getWidgetIds = function () {
    var dashboard_widget_ids = [];
    $("#sortable li[id^='widget']").each(function() {
      dashboard_widget_ids.push($(this).attr('id').split("_")[1]);
    });
    return dashboard_widget_ids;
  }
  $(function() {
    $( "#sortable" ).sortable({
      revert: true,
      update:function(event, ui) {
        $.ajax({
          url:"{{SQL_DASHBOARDS_PREFIX}}/dashboard/{{dashboard.id}}/change_order?order=" + getWidgetIds().join(","),
        });
      }
    });
    $( "ul, li, div" ).disableSelection();

  });
  function reloadQuery(query_id)
  {
    $("#id_query_" + query_id).hide();
    $.ajax({
      url:"{{SQL_DASHBOARDS_PREFIX}}/query/to_highcharts/" + query_id,
      statusCode:{
        200:function(data) {
          $("#id_query_" + query_id).show();
          $("#id_query_" + query_id).html(data);
        },
        202:function(data) {
          $("#id_query_" + query_id).show();
          $("#id_query_" + query_id).html("<p class=\"text-danger\"><b>Error : " + data + "</b></p>");
        }
      }
    })
  }
  </script>
 
<div class="container">
  {% if dashboard_id %}
  <h1>{{dashboard.title}}</h1>
  <ul id="sortable" class="col-lg-12">
    {% for query in dashboard.queries %}
    <li id="widget_{{query.id}}" class="ui-state-default col-lg-{{dashboard.getColumnSize}}" style="floaf:left;">
      {% include "django_sql_dashboards/query_widget.html" %}
    </li>
    {% endfor %}
    <li class="ui-state-default col-lg-{{dashboard.getColumnSize}}" style="floaf:left;">
      {% load crispy_forms_tags %}
      {% crispy form %}
    </li>
  </ul>
  {% else %}
  <div class="row">
    <div class="col-lg-4">
      {% load crispy_forms_tags %}
      {% crispy form %}
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

django_sql_dashboards/templates/django_sql_dashboards/highcharts.html
../highcharts.html

django_sql_dashboards/templates/django_sql_dashboards/home.html
{% extends "base.html" %}

{% block body %}
<div class="container">
  <div class="row">
    {% include "django_sql_dashboards/query_all.html" %}
  </div>
  <div class="row">
    {% include "django_sql_dashboards/dashboard_all.html" %}
  </div>
</div>
{% endblock %}

django_sql_dashboards/templates/django_sql_dashboards/query_all.html
<style>
.listing ul{
  list-style-type: circle;
  padding:0 0 0 10;
  font-size: 12px;
}
.listing .selected {
  font-weight: bold;
}
</style>
{% load pagination_tags %}

<h3><a href="{{SQL_DASHBOARDS_PREFIX}}/query/">Queries</a> <a class="btn btn-success btn-sm" href="{{SQL_DASHBOARDS_PREFIX}}/query/add"><span class="glyphicon glyphicon-plus"></span> Add</a></h3>
{% if query_filter %}
{% autopaginate query_filter.qs 10 as filter_list %}
<div class="col-lg-8 span8">
  <table class="table table-condensed">
    <tr><th>Title</th><th>Creator</th><th>Db</th><th>Action</th></tr>
  {% for obj in filter_list %}
    <tr>
      <td><a href="{{SQL_DASHBOARDS_PREFIX}}/query/edit/{{obj.id}}">{{obj.title}}</a></td>
      <td>{{obj.creator}}</td>
      <td>{{obj.db}}</td>
      <td><a class="btn btn-danger btn-xs" href="{{SQL_DASHBOARDS_PREFIX}}/query/delete/{{obj.id}}" onclick="return confirm('Sure you want to delete {{obj.title|escapejs}}?')"><span class="glyphicon glyphicon-minus"></span> Delete</a></td>
    </tr>
  {% endfor %}
  </table>
  {% paginate %}
</div>
<div class="col-lg-2 span2 well listing" style="overflow: hidden;">
  <form action="" method="get">
    <input type="submit" class="btn btn-primary btn-sm" value="Filter"/>
    {{ query_filter.form.as_p }}
  </form>
</div>
{% endif %}

django_sql_dashboards/templates/django_sql_dashboards/query_custom.html
{% extends "base.html" %}
{% block title %}
{{obj.title}}
{% endblock %}
{% block body %}

<script type="text/javascript" src="{{SQL_DASHBOARDS_PREFIX}}/static/prism.js"></script>
<link href="{{SQL_DASHBOARDS_PREFIX}}/static/prism.css" rel="stylesheet">

<div class="container">
  <h2>{{query.title}}</h2>
  <pre id="id_query_pre"><code class="language-sql">{{query.query}}</code></pre>
  {% load crispy_forms_tags %}
  {% crispy form %}
</div>

{% endblock %}

django_sql_dashboards/templates/django_sql_dashboards/query_editor.html
{% extends "base.html" %}
{% block title %}
Query Editor - {{query.title}}
{% endblock %}
{% block body %}

<script type="text/javascript" src="{{SQL_DASHBOARDS_PREFIX}}/static/prism.js"></script>
<link href="{{SQL_DASHBOARDS_PREFIX}}/static/prism.css" rel="stylesheet">

<div class="container">
  <!-- <h1>Test prism</h1> -->
  <div class="row">
    <div class="col-lg-4 span4">
      {% load crispy_forms_tags %}
      {% crispy form %}
      <div class="row">
        <div id="query_status" class="col-lg-6 span6"></div>
      </div>
    </div>

    <div class="col-lg-8 span8">
      <pre id="id_query_pre"><code class="language-sql"></code></pre>
      <ul class="nav nav-tabs">
        <li class="active"><a href="#id_query_{{query.id}}" data-toggle="tab">Chart</a></li>
        <li><a href="#data" data-toggle="tab">Data</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="id_query_{{query.id}}">
          {% if query.obj %}
          {{query.toHighcharts}}
          {% elif query.error %}
          <br><p><span class="label label-danger">Impossible to load query : {{query.error}}</span></p>
          {% else %}
          <br><p><span class="label label-default">Press run to execute the query</span></p>
          {% endif %}
        </div>
        <!-- <div id="my_chart" class="row"></div> -->

        <div class="tab-pane" id="data">
          {% include "django_sql_dashboards/table.html" %}
        </div>
      </div>
    </div>
  </div>

</div>

<script type="text/javascript">
  var prev_sql_query_1 = undefined;
  var prev_sql_query_2 = undefined;

  function parse_pre()
  {
    sql_query = $("#id_query")[0].value;
    if ((sql_query == prev_sql_query_1) && (sql_query != prev_sql_query_2) && sql_query.length)
    {
      prev_sql_query_2 = sql_query;
      $("#id_query_pre code").html(sql_query);
      Prism.highlightAll();
      $.ajax({
        url: "{{SQL_DASHBOARDS_PREFIX}}/test_query?db=" + $("#id_db :selected")[0].value + "&query=" + encodeURIComponent(sql_query),
        statusCode:{
          200:function(data) {
            $("button[name='run']").show();
            $("button[name='save']").show();
            $("#id_query").parent().removeClass("has-error").addClass("has-success");
            $("#id_query").parent().find("span").remove();
          },
          202:function(data) {
            $("button[name='run']").hide();
            $("button[name='save']").hide();
            $("#id_query").parent().removeClass("has-success").addClass("has-error");
            $("#id_query").parent().find("span").remove();
            $("#id_query").parent().append("<span class=\"help-block\">" + data + "</span>");
          }
        }
      });
    }
    prev_sql_query_1 = sql_query;
    setTimeout(parse_pre, 1000);
  }
  $(document).ready(function() {
    parse_pre();
    $(".collapse").collapse('hide');
  });
</script>
{% endblock %}

django_sql_dashboards/templates/django_sql_dashboards/query_error.html
../query_error.html

django_sql_dashboards/templates/django_sql_dashboards/query_widget.html
<div class="highlight text-left">
  <a href="{{SQL_DASHBOARDS_PREFIX}}/query/edit/{{query.id}}">Edit</a> | 
  <a onclick="reloadQuery({{query.id}})" href="#" onclick="reloadQuery({{query.id}})">Reload</a> |
  {% if request.user == dashboard.creator %}<a href="{{SQL_DASHBOARDS_PREFIX}}/dashboard/{{dashboard.id}}/delete_query/{{query.id}}">Delete</a>{% endif %}
  <div id="id_query_{{query.id}}" class="highlight">
    {{query.toHighcharts}}
  </div>
</div>

django_sql_dashboards/templates/django_sql_dashboards/table.html
<h4>{{obj.title}}</h4>
<table class="table table-condensed">
<tr>
  {% for header in headers %}
  <th>{{header}}</th>
  {% endfor %}
</tr>
{% for row in data %}
<tr>
  {% for cell in row %}
  <td>{{cell}}</td>
  {% endfor %}
</tr>
{% endfor %}
</table>

django_sql_dashboards/templates/django_sql_dashboards/test_query.html
{% if data %}
<table class="table table-condensed">
  <tr><th>Rows</th><th>Select type</th><th>Possible keys</th><th>Key</th><th>Key len</th></tr>
  <tr><td>{{data.rows}}</td><td>{{data.select_type}}</td><td>{{data.possible_keys}}</td><td>{{data.key}}</td><td>{{data.key_ken}}</td></tr>
</table>
{% else %}
{{error}}
{% endif %}